# This is a basic workflow to help you get started with Actions

name: spotlight-build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
           java-version: '8'
           distribution: 'temurin'
           cache: 'maven'
      - name: build with maven
        run: mvn -B -U clean install --file pom.xml
